### ISSUE TITLE
Can't Push Back

### ISSUE THREAD

**Issue by VictorCHC** [BBK-DCSIS-PoP-I-2017-18/Volume-of-a-Cone-Calculator#1]
I tried pushing back but it says I get this message:

![error](https://user-images.githubusercontent.com/32437239/31632894-7af09f98-b2b6-11e7-9cec-7453ba3c1f59.png)

**Comment by jonodrew** [comment]
I don't think you should be able to push to this repo.

**Comment by waffent** [comment]
If it's any help, and if you are after the differences between it and your Volume-of-a-Cone-Calculator-VictorCHC (I'm guessing that's what it's called, I can't see!) repo, then could just make the change by hand - it's only the .yml file that is affected, and you'll probably be changing that anyway.

Or you could do as I did and take your life in your hands and attempt a merge!

**Comment by VictorCHC** [comment]
This got fixed (kind of). I have a new repo that works which I accessed via my DCS e-mail.
